# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dwell.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(905, 132)
        Form.setStyleSheet("QWidget {\n"
"background-color:seashell;\n"
"}\n"
"\n"
"QFrame {\n"
"background-color:#dcb;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"background-color: rgba(0, 0, 0, 60);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_dwell_index = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_dwell_index.sizePolicy().hasHeightForWidth())
        self.lbl_dwell_index.setSizePolicy(sizePolicy)
        self.lbl_dwell_index.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.lbl_dwell_index.setFont(font)
        self.lbl_dwell_index.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_dwell_index.setObjectName("lbl_dwell_index")
        self.horizontalLayout.addWidget(self.lbl_dwell_index)
        self.lbl_dwell_name = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_dwell_name.setFont(font)
        self.lbl_dwell_name.setObjectName("lbl_dwell_name")
        self.horizontalLayout.addWidget(self.lbl_dwell_name)
        self.frm_widget = QtWidgets.QWidget(self.frame)
        self.frm_widget.setStyleSheet("background-color: transparent")
        self.frm_widget.setObjectName("frm_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frm_widget_2 = QtWidgets.QWidget(self.frm_widget)
        self.frm_widget_2.setObjectName("frm_widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frm_widget_2)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frm_widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setStyleSheet("background-color: rgba(0,0,0,60);\n"
"border: none;\n"
"border-radius: 8px;")
        self.doubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setProperty("value", 50.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frm_widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setStyleSheet("background-color: rgba(0,0,0,60);\n"
"border: none;\n"
"border-radius: 8px;")
        self.doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setProperty("value", 20.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.verticalLayout_3.addWidget(self.frm_widget_2)
        self.widget_4 = QtWidgets.QWidget(self.frm_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.widget_4)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setStyleSheet("background-color: rgba(0,0,0,60);\n"
"")
        self.progressBar.setProperty("value", 70)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.lbl_dwell_rest_time = QtWidgets.QLabel(self.widget_4)
        self.lbl_dwell_rest_time.setObjectName("lbl_dwell_rest_time")
        self.horizontalLayout_3.addWidget(self.lbl_dwell_rest_time)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.frm_widget)
        self.btn_dwell_alarm = QtWidgets.QPushButton(self.frame)
        self.btn_dwell_alarm.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_dwell_alarm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dwell_alarm.setStyleSheet("background-color: rgba(0,0,0,60); \n"
"border: none;\n"
"border-radius: 8px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../src/assets/alarm0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dwell_alarm.setIcon(icon)
        self.btn_dwell_alarm.setIconSize(QtCore.QSize(50, 50))
        self.btn_dwell_alarm.setObjectName("btn_dwell_alarm")
        self.horizontalLayout.addWidget(self.btn_dwell_alarm)
        self.btn_dwell_option = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.btn_dwell_option.setFont(font)
        self.btn_dwell_option.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dwell_option.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../src/assets/3-dots-gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dwell_option.setIcon(icon1)
        self.btn_dwell_option.setIconSize(QtCore.QSize(30, 30))
        self.btn_dwell_option.setObjectName("btn_dwell_option")
        self.horizontalLayout.addWidget(self.btn_dwell_option)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setStyleSheet("background-color: transparent; border: none;")
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_dwell_index.setText(_translate("Form", "1."))
        self.lbl_dwell_name.setText(_translate("Form", "Maltoserast"))
        self.doubleSpinBox_2.setSpecialValueText(_translate("Form", "Temperatur"))
        self.doubleSpinBox_2.setSuffix(_translate("Form", " °C"))
        self.doubleSpinBox.setSpecialValueText(_translate("Form", "Dauer"))
        self.doubleSpinBox.setSuffix(_translate("Form", " min"))
        self.lbl_dwell_rest_time.setText(_translate("Form", "4:25 min"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
